import Header from '@/components/Header';
import Footer from '@/components/Footer';

import './globals.css';

import { Karla } from 'next/font/google';
import { Markazi_Text } from 'next/font/google';
import FloatingCartIcon from '@/components/FloatingCartIcon';

const karla = Karla({ variable: '--font-karla', subsets: ['latin'] });
const markazi = Markazi_Text({
	variable: '--font-markazi',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Little Lemon',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${karla.variable} ${markazi.variable}`}>
				<Header />
				<main className="app top-[86.14px] relative z-0 mb-[86.14px]">
					{children}
				</main>
				<Footer />
				{/* <FloatingCartIcon /> */}
			</body>
		</html>
	);
}
