import Header from '@/components/Header';
import './globals.css';
import { Karla } from 'next/font/google';
import { Markazi_Text } from 'next/font/google';

const karla = Karla({ variable: '--font-karla', subsets: ['latin'] });
const markazi = Markazi_Text({
	variable: '--font-markazi',
	subsets: ['latin'],
});

import Footer from '@/components/Footer';

export const metadata = {
	title: 'Little Lemon',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${karla.variable} ${markazi.variable}`}>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
